Nightly docker pipeline

diff --git a/.github/workflows/nightly-build.yml b/.github/workflows/nightly-build.yml
--- a/.github/workflows/nightly-build.yml
+++ b/.github/workflows/nightly-build.yml
@@ -13,4 +13,18 @@ jobs:
         with:
           fetch-depth: 0
       - name: Test Docker Compose
-        run: docker compose up -d
+        id: run_command
+        run: |
+            STATUS_CODE=$(docker compose up -d && curl -s -o /dev/null -w "%{http_code}" localhost:8080)
+            echo "Status code: $STATUS_CODE"
+            # Set the output for GitHub Actions
+            echo "::set-output name=status_code::$STATUS_CODE"
+      - name: Check command success
+        if: ${{ steps.run_command.outputs.status_code == '200' }}
+        run: echo "Command was successful (200)"
+
+      - name: Check command failure
+        if: ${{ steps.run_command.outputs.status_code != '200' }}
+        run: |
+          echo "Command failed with status code ${{ steps.run_command.outputs.status_code }}"
+          exit 1
